### ISSUE TITLE
[MLMD][Bug Bash] Improvements to targeting Artifact cards

### ISSUE THREAD

**Issue by kwasi** [kubeflow/frontend#16]
/area metadata
/area front-end
/priority p0
/assign @kwasi 
/cc @avdaredevil 

## Tasks

* [x] Add a selected radio button to the target card: ([screenshot](https://screenshot.googleplex.com/5yzmVEUggfW))
* [x] Make the whole target card clickable and show a selection cursor.
* [x] (optional) Show a hover state preview on the radio button (ex. a grey or light blue dot)
