### ISSUE TITLE
[MLMD][Bug Bash] Add links for Artifacts shown on the ExecutionDetails page

### ISSUE THREAD

**Issue by kwasi** [kubeflow/frontend#17]
/area metadata
/area front-end
/priority p0
/assign @kwasi 
/cc @avdaredevil 

## Background

This is feature request for ArtifactDetails which is a page within the Pipelines application, rather than shared component. Fixing it Pipelines won't fix it in every place where MLMD Lineage is being used so for the purpose of this bug it's enough to fix the is issue in Pipelines in the short term. 

This issue is being filed in this repo and not pipelines to track finding a more long-term solution where the Artifact list shown on the ExecutionDetails page can be shared. This could be resolved by upstreaming the whole ArtifactDetails to be shared between metadata and pipelines, but that may require more time given that the page components generally expect routing params from the application. 

## Tasks

* [ ] (short-term) Update Artifact list on ExecutionDetails page in KFP to use the `<ArtifactLink />` component for URIs
* [ ] (short-term) Update Artifact list on ExecutionDetails page in KFP to use link name to Artifact details page
* [ ] (long-term) Upstream ExecutionDetails page artifact list component and use in both kubeflow/pipelines and kubeflow/metadata
